#!/usr/bin/python3

import os
import sys
import random
import string

if __name__ == '__main__':
    num = random.randint(1, 154)
    f = open('/Users/michael/github/shakespeare/sonnets.txt', 'r')
    for i in range(1, num*15):
        line = f.readline()
        if (str(num) in line):
            print("Sonnet {0}".format(str(num)))
            print('---------' + ('-' if num >= 100 else ''))
            break

    poem = ''
    for i in range(0, 14):
        line = f.readline().split('\n')[0][2:] + ('\n' if i in [3, 7, 11] else '')

        poem += line

        if (i != 13):
            poem += '\n'
        print(line)

    #Play it out loud -- disabled for your sanity
    #os.system('echo "{0}" | festival --tts'.format(poem))
