#! /usr/bin/python

import os
import sys
import random
import string

if __name__ == '__main__':
    os.chdir('shakespeare')

    num = random.randint(1, 154)
    #print(num)
    f = open('sonnets.txt', 'r')
    for i in range(1, num*15):
        line = f.readline()
        if (str(num) in line):
            print("Sonnet {0}".format(str(num)))
            print('------')
            break

    poem = ''
    for i in range(0, 14):
        line = f.readline().split('\n')[0][2:]
        poem += line
        if (i != 13):
            poem += '\n'
        print(line)

    #Play it out loud -- disabled for your sanity
    #os.system('echo "{0}" | festival --tts'.format(poem))
